### ISSUE TITLE
using `withNavigation` throws an error

### ISSUE THREAD

**Issue by xaviercobain88** [fram-x/FluidTransitions#92] opened 2018-09-03 16:17 UTC
Wrapping a component with `withNavigation` throws the following error:

```
Invariant Violation: Invariant Violation: withNavigation can only be used on a view hierarchy of a navigator. The wrapped component is unable to get access to navigation from props or context.

This error is located at:
    in withNavigation(TransitionableBottomSheet) (at Screen1.js:35)
    in RCTView (at View.js:60)
    in View (at Screen1.js:26)
    in Screen1 (at FluidTransitioner.js:367)
    in RCTView (at View.js:60)
    in View (at createAnimatedComponent.js:154)
    in AnimatedComponent (at TransitionRouteView.js:39)
    in TransitionRouteView (at FluidTransitioner.js:361)
    in RCTView (at View.js:60)
    in View (at TransitionItemsView.js:106)
    in TransitionItemsView (at FluidTransitioner.js:210)
    in RCTView (at View.js:60)
    in View (at Transitioner.js:141)
    in Transitioner (at FluidTransitioner.js:71)
    in FluidTransitioner (at createFluidNavigator.js:35)
    in FluidNavigationView (at createNavigator.js:59)
    in Navigator (at createNavigationContainer.js:376)
    in NavigationContainer (at App.js:11)
    in App (at registerRootComponent.js:35)
    in RootErrorBoundary (at registerRootComponent.js:34)
    in ExpoRootComponent (at renderApplication.js:33)
    in RCTView (at View.js:60)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:60)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:32)

This error is located at:
    in NavigationContainer (at App.js:11)
    in App (at registerRootComponent.js:35)
    in RootErrorBoundary (at registerRootComponent.js:34)
    in ExpoRootComponent (at renderApplication.js:33)
    in RCTView (at View.js:60)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:60)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:32)
```

**Comment by chrfalch** [comment] 2018-09-04 07:04
Hi, @xaviercobain88 - thanks for submitting an issue. To be able to investigate we need a little more context. The best thing would be a short snack on Expo - or a description of what you're trying to do, why and how you reproduce this issue. Otherwise it'll be closed :-)

**Comment by israelidanny** [comment] 2018-09-19 09:05
@chrfalch I'm also getting this issue. Didn't have to do anything special, just apply `withNavigation` to any element other than the screen itself.

**Comment by chrfalch** [comment] 2018-09-19 09:06
@israelidanny: But I need to know what you are trying to accomplish - why use `withNavigation()` - to get a clearer understanding of the use case.

**Comment by israelidanny** [comment] 2018-09-19 09:09
@chrfalch I'm using `withNavigation()` for its' official documented use:
To be able to use the `navigation` prop without having to drill it down through the whole tree to my specific component.

**Comment by chrfalch** [comment] 2018-09-19 09:10
Ok, would it be possible to create a simple reproduction using http://snack.expo.io?

**Comment by israelidanny** [comment] 2018-09-19 09:35
This seems to reproduce it (however instead of showing the error message it loses connection with device):
https://snack.expo.io/HkpaLcJYQ

**Comment by chrfalch** [comment] 2018-09-19 13:03
Try adding the following (satic router...) to the exported class (just like in the examples):

```js
export default class App extends Component {
  static router = Navigator.router;
  render() {
    return (
       <Navigator/>
    );
  }
}
```

**Comment by Rekian** [comment] 2018-09-20 07:17
im also getting this issue
im trying to call "this.prop.navigation." inside component by importing withNavigation

**Comment by chrfalch** [comment] 2018-09-20 07:53
I've tested out the snack in my debugger, and the same error occurs when using `createStackNavigator` as with FluidNavigator. You should all probably try to find out if this is an issue with your navigation setup. I'm closing this one for now. @Rekian @israelidanny @xaviercobain88

**Closed by chrfalch** 2018-09-20 07:53 UTC
Labels: Reproduction Needed

**Comment by stpch** [comment] 2018-10-03 02:04
Here is a reproducible example: https://snack.expo.io/rkkqMjWqQ

If you go to `Router.js` and use `createStackNavigator` instead, it'll work. I used `react-navigation-fluid-transitions@2.6` because newer versions throw a dependency error in Expo.
