### ISSUE TITLE
Splash screen appears for a moment when transitioning on android

### ISSUE THREAD

**Issue by marceloHashzen** [fram-x/FluidTransitions#34] opened 2018-05-30 00:44 UTC
Hello everyone, I've made a little demo app that is composed os two screens, the first with just a text a a button, and the second with a header and a camera view.
I'm using the FluidNavigator to fade through the screens, but when the transition happens, I can see for a moment the app's splashscreen on the background. This happens only on android, on ios it works fine.

My package.json is as follows:

```
"dependencies": {
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-camera": "^1.1.4",
    "react-native-vector-icons": "^4.6.0",
    "react-navigation": "^2.0.1",
    "react-navigation-fluid-transitions": "^0.2.0"
  },
```

I'm using Animated to create interpolations of color and scale at the button. I've also tried to set a background color on the second screen, but had no effect.
Here are two videos of the app:

Android: [https://www.youtube.com/watch?v=FGAHmNoABfo&feature=youtu.be](https://www.youtube.com/watch?v=FGAHmNoABfo&feature=youtu.be)

iOS: [https://www.youtube.com/watch?v=aR2QCpS0OJ0&feature=youtu.be﻿](https://www.youtube.com/watch?v=aR2QCpS0OJ0&feature=youtu.be﻿)

**Comment by msevestre** [comment] 2018-05-30 01:07
Can you create a snack so that the issue can be reproduced?

**Comment by chrfalch** [comment] 2018-06-07 06:19
@marceloHashzen We need reproductions, will be closing this issue if there are no further activity soon :-)

**Comment by marceloHashzen** [comment] 2018-06-07 14:00
Sorry for the delay. I've uploaded all my code to github:

[https://github.com/marceloHashzen/barcode](https://github.com/marceloHashzen/barcode)

**Comment by chrfalch** [comment] 2018-06-11 07:40
Hi @marceloHashzen! Is it possible for you to create a simple reproduction using https://snack.expo.io? It'll help us isolate the issue you are experiencing.

**Comment by chrfalch** [comment] 2018-06-20 07:10
Due to lack of activity I'm closing this one for now.

**Closed by chrfalch** 2018-06-20 07:10 UTC
Labels: Reproduction Needed
