### ISSUE TITLE
Old element is showing during the navigation back transition

### ISSUE THREAD

**Issue by whdckszxxx** [fram-x/FluidTransitions#105] opened 2018-09-21 17:39 UTC
First of all, thanks for great package.

Version: 0.2.6
RN Version: 0.57.0

I'm using `Transition` element to show scaling out/in of `Image` element during the transition between screens. It works great except when I change source of shared image element. The source was determined by redux state and the sources of shared elements are referencing same state. So I thought changing both elements source via redux state will be fine but it was not. During backward transition old image(before the state change) was showing.

And here is my question
1. Is there any way to show newer image in backward transition?
2. Is it a limitation or a bug?

I don't know if you guy understand what I'm trying to explain because I'm not good at English.
So, if you want me to clarify anything or provide more information please let me know!

**Comment by chrfalch** [comment] 2018-09-22 08:45
Hi @whdckszxxx - if you could provide a quick reproduction of the problem using snack.expo.io, we might be able to help you.

**Comment by whdckszxxx** [comment] 2018-09-23 08:31
@chrfalch Hi, I just made a simple reproduction here 
https://snack.expo.io/HJLy1REt7

**Comment by chrfalch** [comment] 2018-09-23 09:34
Thanks, @whdckszxxx. I'm having a little bit of trouble getting the sample to work, it fails when pressing back. I'm also unsure what to expect and where to look for errors.

**Comment by chrfalch** [comment] 2018-09-23 15:45
This is kind of expected. The reason is that we are saving the old transition element and reusing it for performance. I'll see if we can find a solution for this one.

**Comment by whdckszxxx** [comment] 2018-09-23 16:02
I see. Thank you

**Comment by proof666** [comment] 2018-10-08 12:11
Hi!
I also ran into this issue. I use this library in grocery list app. The application has grocery lists, when you go to the list details, list component move to header (shared) and items in this list are displayed with appearence animation. If you go to the items and mark several items as "done" - they move to the bottom of list. After that, if return to the lists (back) — the animation is played back whith its original state (before making any changes in item). 

It turns out the library can only be used with components that do not change between animations. This behavior kills my idea and makes it impossible to use this library.

If there are any plans for this issue? Mayby some workaround like force recalculation or...?

PS: Let me now if you need more details about my use case

**Comment by chrfalch** [comment] 2018-11-05 13:13
Should be fixed in #130. If you are able to clone and test this I'd be really happy!

**Closed by chrfalch** 2018-11-05 13:13 UTC
Labels: bug

**Comment by chrfalch** [comment] 2018-11-05 13:37
Should be fixed in the latest release 0.2.73.
