### ISSUE TITLE
willBlur, didBlur listener not call

### ISSUE THREAD

**Issue by dtuan** [fram-x/FluidTransitions#9] opened 2018-04-17 17:07 UTC
Thanks for your great work, 

Please help me with this issue, note that: it works when I changed to use StackNavigator.

Also the function "this.props.navigation.isFocused" in the list page return not correct, step:
 1. Open list page : isFocused = true -> correct
 2. Select an item to go to detail page: isFocused of list page = false -> correct
 3. Go back to list page: isFocused now always false -> wrong

Many Thanks,

**Comment by chrfalch** [comment] 2018-04-18 06:30
Hi @dtuan! Thanks for contributing back with your findings. Would you please be so kind to create a simple reproduction of the issue with a short snack? (https://snack.expo.io).

**Comment by chrfalch** [comment] 2018-04-25 07:25
@dtuan I've had a look at your example but are having some troubles finding where in the code these events are generated. Will continue to investigate!

**Comment by dtuan** [comment] 2018-04-26 07:58
@chrfalch thank you, really appreciate your work,

**Comment by reekris** [comment] 2018-08-20 12:46
I'm still having this issue with the latest version (0.2.3) along with the latest version of react-navigation (2.11.2). That is, willFocus and willBlur events stop firing when navigating back and forth between screens.

I created a new snack with a reproduction of the issue: https://snack.expo.io/rkVKU4O8Q

When navigationg between Master and Detail Screens there should be a log when the different events are triggered. It seems like the correct events are fired when going from Master to Detail. But when going back to Master the didFocus event of the Master Screen is never fired. I guess this could the reason subsequent events are not triggered correctly?

When switching to the built in Stack Navigator ( By uncommenting line 67 and commentiung out line 68 in the snack) the didFocus event is triggered when going back rom Detail to Master and subsequent events seems to fire correctly.

Let me know if the snack is unclear in any way and thanks for a great library!

**Comment by chrfalch** [comment] 2018-08-20 12:51
Ok ;-) Sorry for closing it down. The problem is that I'm unable to find out where these events are created and what to do with them... Would love some help on this one, @reekris?

**Comment by reekris** [comment] 2018-08-20 13:30
I had a look around the code and I'm not entirely sure how the event system works either tbh :)

But I compared the code between createFluidNavigator.js and the built in StackView.js and noticed a difference in how the onTransitionEnd callbacks are set up. Specifically there is a check wether to perform `completeTransition` or not.

Here is how it locks in StackView.js:
https://github.com/react-navigation/react-navigation-stack/blob/d6b1f5c9673e7dd5da92cfa4e34fc087ab8e5c01/src/views/StackView/StackView.js#L35

In createFluidNavigator.js there is an added check for ```!lastTransition.navigation.state.isTransitioning````
https://github.com/fram-x/FluidTransitions/blob/2160a0a0a390dc36e59496d468a4bf1253df10ed/src/createFluidNavigator.js#L45-L48

I tried removing that extra check and it seems to have fixed the issue. Now the didFocus and didBlur events are fired and subsequent events seems to work.

Although I might have broken something else :) I guess there is a reason why that check is there?

**Comment by reekris** [comment] 2018-08-20 17:57
I poked around the react-navigation commit history and found this pull request that removes the second check from the built in Stack navigator: 

https://github.com/react-navigation/react-navigation/pull/4115

Maybe it should be removed in this library as well?

**Comment by chrfalch** [comment] 2018-08-28 12:46
Should be fixed in PR #83, release 0.2.5 - anyone cares to test and verify?

**Closed by chrfalch** 2018-08-28 12:46 UTC

**Comment by elzii** [comment] 2019-01-29 00:21
Experiencing this again with `react-navigation@3.1.0`

**Comment by WillyRamirez** [comment] 2019-11-28 17:16
@elzii for me this worked

`  constructor(props) {
    super(props);
    this.listener = this.props.navigation.addListener('didBlur', () => (
      // do stuff  
  ));
  }`

but the `<NavigationEvents />` didn't
